server:
  port: 11111
spring:
  # Redis服务连接配置
  redis:
    # 服务地址
    host: 127.0.0.1
    # 服务器连接端口
    port: 6379
    # 服务器连接密码(默认为空)
    password:
  cache:
    redis:
      # 基于注解的redis缓存使用的缓存时间配置
      time-to-live: 60000
  datasource:
    url: jdbc:mysql://localhost:3307/micro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy:
          #避免将驼峰命名转换为下划线命名(jpa会自动把实体类的驼峰字段转为 _ 连接的字段名)
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
